org.gradle.jvmargs=-Xmx768m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.injected.testOnly=false
android.enableR8.fullMode=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=CinnamonBun,37,37.2
org.gradle.warning.mode=all
org.gradle.caching=false
org.gradle.daemon=false
org.gradle.logging.level=info
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=9910
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=9910