-libraryjars "C:\Users\i\AppData\Local\Android\Sdk\platforms\android-37.2\android.jar"
-optimizationpasses 7
-dontusemixedcaseclassnames
-overloadaggressively
-repackageclasses "a"
-allowaccessmodification
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute ""
-verbose