plugins {
    id "java"
}

java {
    targetCompatibility = JavaVersion.VERSION_24
    sourceCompatibility = JavaVersion.VERSION_24
}

jar {
    manifest {
        attributes('Main-Class': 'com.android.signapk.SignApk')
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}